project:
  type: website
  output-dir: docs

website:
  title: "Henderson Vo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - cv.qmd
      - flex.qmd
      - projectpage.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

