---
title: "My travel portfolio"
toc: false
---

Placeholder (free for all)

interactive map here?

# include sections

```{r}
#| echo: false
#| message: false
#| warning: false

# load packages
library(leaflet)
library(tidyverse)

# load and clean data
gps <- read_csv("data/photo_gps.csv")
  

```

```{r}
# initialize map ----
site_map <- leaflet() |>  
  
  # add base map tiles (use `addTiles()` for Google maps tiles, OR `addProviderTiles()` for 3rd party base maps: https://leaflet-extras.github.io/leaflet-providers/preview/) ----
  addProviderTiles(providers$Esri.WorldImagery, group = "ESRI World Imagery") |>  
  addProviderTiles(providers$Esri.OceanBasemap, group = "ESRI Oceans") |> 
  
  # add mini map ----
  addMiniMap(toggleDisplay = TRUE, minimized = TRUE) |> 
  
  # set view over Santa Barbara Channel ----
  setView(lng =  -119.83, lat = 34.44, zoom = 9) |> 
  
  # add MPA markers ----
  addMarkers(data = gps, group = "MPA Sites",
             lng = ~longitude, lat = ~latitude,
             popup = paste("Site Name:", gps$location, "<br>",
                           "Coordinates (lat/long):", gps$latitude, ",", gps$longitude)) |> 
  
  # add layers control (toggle base map tiles & markers based on group IDs) ----
  addLayersControl(
    baseGroups = c("ESRI World Imagery", "ESRI Oceans"),
    overlayGroups = c("MPA Sites", "Non-MPA Sites"))


# print map ----
site_map
```

